# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ForestFireSeverityEstimation
                                 A QGIS plugin
 Forest fire severity estimation using DNBR index from Sentinel-2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-10
        copyright            : (C) 2022 by David Hernández López
        email                : david.hernandez@uclm.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ForestFireSeverityEstimation class from file ForestFireSeverityEstimation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .forest_fire_severity_estimation import ForestFireSeverityEstimation
    return ForestFireSeverityEstimation(iface)
